# General Jekyll Config
highlighter: rouge
url: http://maryletteroa.github.io
lsi: false
exclude: [LICENSE, CNAME, README.md, .gitignore, Gemfile, Gemfile.lock]
paginate: 10
paginate_path: "/blog/page:num/"

plugins:
  - jekyll-paginate
